### PR TITLE
Feature to create swapfile, & fix to separate home partitions.

### PR DESCRIPTION
**Pull request by MarkSilverMedia**
Hi, Jody.

I've been taking a look at your code for the revenge installer for a little over a week now, and I'd be more than happy to contribute some of my own efforts to the installer framework! I've made two changes thus far that can be reflected when comparing your repo to my fork. First of all, I added the option for the user to create a swapfile if they so chose, which I set to be a gigabyte in size on the root partition for the time being. Secondly, I fixed an error in the code that mounted /mnt/home to the same partition that root was mounted to whenever the user chose to create a separate home partition.

If you have any questions or feedback regarding my changes, please feel free to let me know. ;)

-Mark Silver.

### CODE REVIEW

**Comment by obrevenge** [comment]
Thank you! I will check the changes out and merge them as long as all works well. I was actually planning on adding the option for a swapfile, so that is a very welcome addition!

**Comment by obrevenge** [comment]
Looks excellent! Thank you for fixing my mistake with the home partition! It has been merged!

**Comment by MarkSilverMedia** [comment]
Sounds good! Glad you liked my changes! One thing I'd suggest you add to it though, mainly because I've yet to figure out how to do this, is a back-and-forth progress bar (like the one that runs during installation) for when the installer is creating the swap file, as it has taken between 5-8 seconds in my testing, & may leave the end-user wondering whether that process is functioning. In the meantime, I'm gonna be trying some different things out on the testing branch of my fork of this repo, and I intend to send another pull request your way once I implement the ability to install grub on configurations with an EFI System Partition mounted at /boot/efi. ;)

EDIT: I came across an issue when I tested the updated installer which made /etc/fstab look for the swapfile in the /mnt directory. I'll test to see if adding the swapfile to /etc/fstab using arch_chroot fixes that issue.

**Comment by obrevenge** [comment]
Ok, I will add the progress bar, not a problem. Using DD for creating the swapfile is a little slow, but the most reliable. I didn't have the issue you described in my testing, but performing the action in a chroot shouldn't hurt anything if it does solve a problem.

**Pull request merged**
